# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://github.com.narek-booth/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Narek Galustyan
  url:               https://ru.linkedin.com/in/narek-galustyan-239a2482
  email:             narek@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
